### ISSUE TITLE
response to hb2

### ISSUE THREAD

**Issue by timm** [icsme2016/icsme2016.github.io#1]
Planned news text:
- "ICSME co-chairs respond to House Bill 2."

Text to  add:

---
# ICMSE'16 general chairs respond to House Bill 2

Some submitters to ICSME'16 have asked about our response to the North Carolina Legislature's recent "House Bill 2," which blocks cities from allowing transgender individuals to use public multi-occupancy bathrooms consistent with their gender identity -- as well as restricting cities from passing nondiscrimination laws more broadly.

Our response is as follows.

<a href="http://blog.amnestyusa.org/africa/the-state-of-lgbt-rights-worldwide/"><img width=300 align=right src="http://blog.amnestyusa.org/wp-content/uploads/2014/05/LGBT.jpg"></a>

ICSME'16  will respect and accept and gladly welcome all members of the  international research community regardless of their  race, sexual orientation or gender identity. 

We believe HB2 to be ill-conceived, rude, and ridiculous. Further, we believe that it will soon be repealed and, in the meantime, much government money and time will be wasted on this silliness. 

This law, written in extreme haste, is so poorly designed that it is unenforcable. "We're not checking birth certificates. We just don't have the police power to be able to do that in bathrooms", says [local police representatives](http://www.motherjones.com/politics/2016/04/north-carolina-lgbt-bathrooms-hb2-enforcement).

The law lacks support within Raleigh and has been widely criticized by local community leaders: 
- The Mayor of Raleigh, [Nancy McFarlane](https://www.raleighnc.gov/home/news/content/CorNews/Articles/MayorStatementHB2.html) writes: “Raleigh... is a place where people respect each other’s differences and understand that those differences make us stronger.  ... Raleigh will always be open to everyone. **Everyone.** We will continue to support all of our businesses, citizens and visitors with the utmost respect, regardless of race, color, religion, age, national origin, sex, sexual orientation, gender identity or disability. ... We will continue to work together, cherish each other and move forward with dignity and respect.”
- The President of the University of North Carolina System, [Margaret Spellings](http://www.dailytarheel.com/article/2016/04/spellings-clarifies-hb2-compliance) stressed that all the current non-discrimination policies at this university will remain in place. She writes "We pride ourselves as institutions of diversity, inclusion, academic freedom, free speech, free expression. Anything that undermines that is a concern to me."

As to the venue for ICSME'16, the Raleigh Marriott City Center writes:
- "As a private organization we are not bound by the [HB2] ruling – As a hospitality entity our role is to make everyone feel like they are coming home."
-  "[A]s a place of hospitality, we pride ourselves on being inclusive and welcoming to all. We appreciate the [ICSME] attendees and per our non-discrimination policies all of our guests and associates will remain respected in our hotel."

We believe that the best response to the nonsense of HB2 is to show the world the value of diverse minds meeting to tackle hard and fascinating and pressing current problems. As such, we invite you to join us in October and sincerely hope that you will choose to do so. In the meantime, please do not hesitate to contact us should you have any questions about the conference or its venue.

Nick Kraft and Tim Menzies
General Co-Chairs of ICSME'16

<br clear=all>

**Comment by nkraft** [comment]
One correction:

"is supported or endorsed by the ICSME'16 organizers." --> "is neither supported nor endorsed by the ICSME'16 organizers."

One addition:

Let's add a snippet of the language that the Marriott sent. Maybe add this between the Raleigh and NC State parts:

The Raleigh Marriott City Center writes:

"[A]s a place of hospitality, we pride ourselves on being inclusive and welcoming to all. We appreciate the [ICSME] attendees and per our non-discrimination policies all of our guests and associates will remain respected in our hotel."

"As a private organization we are not bound by the [HB2] ruling – As a hospitality entity our role is to make everyone feel like they are coming home."

Two suggestions:

"The entire team organizing ICSME'16 assert that" --> "The general co-chairs are allies of the LGBTQ community and assert that"

"We are not even sure if those laws are actionable. and look" --> "It is unclear whether or how HB2 is actionable. We look"

**Comment by nkraft** [comment]
Also:

"international academic community" --> "international research community"

**Comment by timm** [comment]
@nkraft 

over to you

t

**Comment by timm** [comment]
![image](https://cloud.githubusercontent.com/assets/29195/14448344/df38d9e6-0035-11e6-83c1-8dbb52ee2378.png)
